### ISSUE TITLE
Best approach to get an ADC to serial example working on a board/chip like F1x0?

### ISSUE THREAD

**Issue by crosswick** [CommunityGD32Cores/gd32-pio-projects#3]
Hi - I see that in terms of ADC examples, there's currently only two for the F30x range.

When I simply open the polling one of those and add my F1x0 board to the platform.ini and the include, I get a bunch of errors, amongst which:

```
src/main.c:64:22: error: 'GPIO_MODE_AF_PP' undeclared (first use in this function); did you mean 'GPIO_MODE_AF'?
   64 |     gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_9);
      |                      ^~~~~~~~~~~~~~~
      |                      GPIO_MODE_AF
src/main.c:64:22: note: each undeclared identifier is reported only once for each function it appears in
src/main.c:65:22: error: 'GPIO_MODE_IN_FLOATING' undeclared (first use in this function); did you mean 'GPIO_MODE_ANALOG'?
   65 |     gpio_init(GPIOA, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, GPIO_PIN_10);
      |                      ^~~~~~~~~~~~~~~~~~~~~
      |                      GPIO_MODE_ANALOG
src/main.c: In function 'rcu_config':
src/main.c:102:29: error: 'RCU_ADC0' undeclared (first use in this function); did you mean 'RCU_ADC'?
```

Do the APIs for these chips indeed differ in this way? I'd be happy to learn the best approach here, thanks in advance.

**Comment by maxgerhardt** [comment]
Yeah using the different API styles for analog reads [can be done](https://github.com/CommunityGD32Cores/ArduinoCore-GD32/blob/832a32be3649251b1faae963ea9b4b79b24c641e/cores/arduino/analog.cpp#L126-L186), the code will just get a but messy with it. I'll expand the examples.

**Comment by maxgerhardt** [comment]
If your goal is to have one clean project with code only targeting the F1x0, you should be taking the code from the official SPL example that's always in the SPL firmware folders: https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/main/GD32F1x0/GD32F1x0_Firmware_Library_V3.3.2/Examples/ADC/ADC0_software_trigger_regular_channel_polling/main.c

Most of the SPL project here are based on these projects, and slightly modified to work in a few more configurations.

**Comment by crosswick** [comment]
Ah great, thank you, that will certainly do for now for me.

**Comment by crosswick** [comment]
So far I'm copying over code from that to the SPL USART example, and am finding this error:

![image](https://user-images.githubusercontent.com/526402/148466552-5bc5968c-9d5a-4e4a-8baf-9840af842c7f.png)

Perhaps this is something unique introduced in the 3.3.2 firmware, and not yet supported somehow?

**Comment by maxgerhardt** [comment]
Oops yes, the SPL repo currently works with the older firmware package version 3.1.0, not 3.3.2 (https://github.com/CommunityGD32Cores/gd32-pio-spl-package/blob/main/gd32/cmsis/variants/gd32f1x0/gd32f1x0.h#L6-L13). You should be using the suggested `ADC_EXTTRIG_REGULAR_SWRCST` there for the older version.

**Comment by crosswick** [comment]
Alright - then it still is not working somehow; it seems to lock up on the adc_channel_sample function call here:

 ```
 //int i = 0;
    while (1)
    {
        adc_value[0] = adc_channel_sample(ADC_CHANNEL_1);
        printf("Hello World\n");
        //printf("GPIOA1 is seeing a value of: %u\n", adc_value[0]);
        //printf("a usart transmit test example! iteration %d\n", i++);
        delay_1ms(500);
    }
```
Because this doesn't output anything over serial... when I comment out that adc_value line it does output the HelloWorlds

**Comment by crosswick** [comment]
I think there might be some more dependencies? The 'ADC software trigger regular channel polling' example did not exist yet in 3.1.0

**Comment by maxgerhardt** [comment]
The closest reference example is https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/main/GD32F1x0/GD32F1x0_Firmware_Library_v3.1.0/Examples/ADC/Temperature_Vref_Vbat/main.c for V_TEMP and it does the adc_config() a bit differently, especially with `adc_external_trigger_config(ADC_INSERTED_CHANNEL,ENABLE);` and `    adc_inserted_channel_config(0,ADC_CHANNEL_16,ADC_SAMPLETIME_239POINT5);` for the trigger configuration.

I'll update the SPL package to 3.3.1 quickly so that these issues are resolved.

**Comment by maxgerhardt** [comment]
Please open a [CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and execute `pio platform update gd32`, then try the project https://github.com/CommunityGD32Cores/gd32-pio-projects/tree/main/gd32-spl-adc-polling-gd32f1x0

**Comment by crosswick** [comment]
Will do, afk now

**Comment by crosswick** [comment]
I'm getting misformatted usart messages:

`<␀␜�␎␀␇�␞�␇     �X␃�␜␀␏�␀��<@␆�␀� �␜�␎u␇␅␝ �8�<�␜`␇�␜B␏�␃�␁�␜Ȱ�␜��8@␏�`�␀�<␀␏␀␇�␞�␀␃␆�:�␝�␕0␌␀␞�␀␃␃�␃�␝�J␆���␃�8@��␁ ��␝�<␀␇�`

**Comment by maxgerhardt** [comment]
Oh, I forgot to se `monitor_speed = 115200` at the top, correcting..

**Comment by crosswick** [comment]
Yes that did the trick. Not that it's super important for my current application, but: I am seeing a reported value of 2.11V when I input 2V according to my bench power supply

**Comment by maxgerhardt** [comment]
When you replace `ADC_SAMPLETIME_7POINT5` with `ADC_SAMPLETIME_239POINT5` in the code, does it get more accurate? What does the connection to the analog-power rails VDDA and VSSA look like? It should have some decoupling / filtering going on like [this](https://electronics.stackexchange.com/questions/537261/why-place-an-inductor-between-vin-and-vdda-avdd) in the hardware.

**Comment by crosswick** [comment]
Looks like it was down to the 3.2V from my USB-USART dongle. When I power the board via USB the value is much closer to 2V, namely 1.98V

**Comment by maxgerhardt** [comment]
The microcontroller (every gd32 chip basically) has the capability to measure a V_REFINT internal reference voltage (1.2V per [user manual](https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/main/GD32F1x0/GD32F1x0_User_Manual_EN_Rev3.4.pdf) page 239) and with that one can get the actual supply voltage and correct the ADC count -> voltage conversion `adc_value[i] * 3.3f / 4095.f` with respect to the statically-assumed `3.3V` value there. There is example code for reading `VREFINT` (and `VTEMP` and `VBAT`) at https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/main/GD32F1x0/GD32F1x0_Firmware_Library_v3.1.0/Examples/ADC/Temperature_Vref_Vbat/main.c, that plus a bit of math will make the measurements much more correct -- not implented in the example for simplicity though.

**Comment by crosswick** [comment]
Good to know! As far as I'm concerned this issue is now resolved, thanks again for your swift assistance
